name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set version
      id: version
      run: |
        output=$(date -u '+%Y%m%d%H%M%S')
        echo "date_version=$output" >> $GITHUB_OUTPUT
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: devshred/ebook-convert
        tags: latest, ${{steps.version.outputs.date_version}}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
